name: Build and deploy Project Service to Azure Web App - perpustakaan-project

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  APP_PATH: services/project_service

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python version
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Create venv and install deps (project_service)
        working-directory: ${{ env.APP_PATH }}
        run: |
          python -m venv antenv
          source antenv/bin/activate
          pip install -r requirements.txt

      - name: Upload artifact for deployment (project_service only)
        uses: actions/upload-artifact@v4
        with:
          name: project-service
          path: |
            ${{ env.APP_PATH }}
            !${{ env.APP_PATH }}/antenv/
          if-no-files-found: error

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: project-service
          path: project-service

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_38E68F07066942A9AEEB0BB9F73DB3D1 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_026A074FC224473481688C1080DE9553 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_C7B0278BBEAF4358876FD971F71D32A6 }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: perpustakaan-project
          slot-name: Production
          package: project-service
